---
# Super-Linter Configuration
# Documentation: https://github.com/github/super-linter

# General Settings
DEFAULT_BRANCH: main
VALIDATE_ALL_CODEBASE: false  # Only validate changed files in PRs
DISABLE_ERRORS: false         # Fail on linting errors

# JavaScript/Node.js Validation
VALIDATE_JAVASCRIPT_ES: true
VALIDATE_JAVASCRIPT_STANDARD: false  # Using ESLint instead
VALIDATE_TYPESCRIPT_ES: true
VALIDATE_TYPESCRIPT_STANDARD: false  # Using ESLint instead

# JSON Validation
VALIDATE_JSON: true
VALIDATE_JSONC: true

# YAML Validation
VALIDATE_YAML: true

# Markdown Validation
VALIDATE_MARKDOWN: true

# Shell Script Validation
VALIDATE_BASH: true
VALIDATE_BASH_EXEC: true

# Docker Validation
VALIDATE_DOCKERFILE: true
VALIDATE_DOCKERFILE_HADOLINT: true

# GitHub Actions Validation
VALIDATE_GITHUB_ACTIONS: true

# HTML/CSS Validation (if needed)
VALIDATE_HTML: false
VALIDATE_CSS: false

# Python Validation (if needed)
VALIDATE_PYTHON: false
VALIDATE_PYTHON_BLACK: false
VALIDATE_PYTHON_FLAKE8: false
VALIDATE_PYTHON_ISORT: false
VALIDATE_PYTHON_MYPY: false
VALIDATE_PYTHON_PYLINT: false

# Additional Language Support
VALIDATE_GO: false
VALIDATE_JAVA: false
VALIDATE_KOTLIN: false
VALIDATE_LUA: false
VALIDATE_PERL: false
VALIDATE_PHP: false
VALIDATE_RUBY: false
VALIDATE_RUST: false

# Linter-specific configurations
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
MARKDOWN_CONFIG_FILE: .markdownlint.json

# Output Settings
LOG_LEVEL: INFO              # Options: TRACE, DEBUG, INFO, NOTICE, WARN, ERROR, FATAL
CREATE_LOG_FILE: true
OUTPUT_FORMAT: tap          # Options: tap, json, checkstyle
OUTPUT_FOLDER: super-linter.report
OUTPUT_DETAILS: detailed    # Options: simpler, detailed

# Performance Settings
PARALLEL: true              # Run linters in parallel
MULTI_STATUS: true         # Create individual status checks for each linter

# Filter Settings
FILTER_REGEX_EXCLUDE: .*node_modules/.*|.*\.git/.*|.*dist/.*|.*build/.*|.*coverage/.*

# GitHub Integration
GITHUB_TOKEN: ${{ github.token }}
GITHUB_DOMAIN: github.com

# Suppress specific warnings (uncomment if needed)
# SUPPRESS_POSSUM: true
# SUPPRESS_FILE_TYPE_WARN: true