# ESLint configuration for Super-Linter
# This file is used by GitHub Super-Linter

extends:
  - eslint:recommended

env:
  node: true
  es2021: true
  jest: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  # Already configured in project's ESLint
  # Super-Linter will use this as override